### ISSUE TITLE
Update to AZ CLI 2.x ?

### ISSUE THREAD

**Issue by kjhosein** [BuildAzure/azure-region-map#3]
Hello - any plans to update to use the 2.x version of the CLI? (new command: `az account list-locations --output json`)

If not, perhaps include this command in the FAQ? 
Thanks!

**Comment by crpietschmann** [comment]
The JSON output of the CLI 1 vs CLI 2 is different. I looked at it awhile back. I'll revisit this soon. Thanks! :)

**Comment by crpietschmann** [comment]
I have added the CLI 2 command to the FAQ popup. However, I'm still copying the v1 JSON when I update the map. The JSON output of both is compatible, but the v1 JSON still includes a list of the Azure Services support in that region. I don't do anything with this in the map right now, but seems useful just in case. :)
